### ISSUE TITLE
How to speed up execution？

### ISSUE THREAD

**Issue by dingtine** [locuslab/trellisnet#6]
ihave just have 4000 parametes , its run so slow

**Comment by shaojieb** [comment]
Yes, as it's a stacked weight-tied model, the # of layers can hugely affect the speed. 

As we suggested in the paper, there are two ways to quickly reduce the # of layers (and thus make the model faster): 1) use larger kernel size (the current default is 2) and broaden the receptive field; or 2) use dilated convolution.

Both of these can be specified using the argparse flag on the command line.
